### ISSUE TITLE
Image loading at run time

### ISSUE THREAD

**Issue by graphicstone** [graphicstone/UserInfoView#1]
Currently you can set the image using XML but not through code during run time. Need to load the image using glide or any other library or if anything better comes to your mind that is also welcome. The main objective is to load the image during run time from network or local storage, whichever suits the user.

**Comment by AlinaStepanova** [comment]
Hi @graphicstone, I can do this, please assign to me

**Comment by graphicstone** [comment]
Absolutely! If you have any questions let me know.

**Comment by AlinaStepanova** [comment]
@graphicstone please review a pull request =)

**Comment by graphicstone** [comment]
Sure, just give me some time, I'll review it and update the PR.
